### ISSUE TITLE
Pole chudes

### ISSUE THREAD

**Issue by bodrovis** [ImprovementMajor/NewNew#4]
https://github.com/ImprovementMajor/NewNew/commit/86b082659ab250c35f705532f8bde32bcc579bcb

TODO @bodrovis

**Comment by bodrovis** [comment]
`guess_character=guess_character[0]` - actually, this line does not open anything yet. It simply takes the first letter from the user's input, because previously we have `guess_character = input("Your letter is: ")`.

But can a user enter not one but many characters, including some gibberish like `abcdef`? Sure, why not - we can't prevent the user from doing so. However, we need only a single character from the user's input. This is dictated by the rules of our game: the player should guess character-by-character, s/he can't input multiple characters at once.

That's why we say `guess_character[0]` which means we'll take only `a` from the string `abcdef`, for example. We then store this letter entered by the user, and only then we check if the user has made a correct guess or not (starting from line 37 and below).

**Comment by bodrovis** [comment]
`guessed_any = False`

Each loop of the `while word != guess_word:` is a player's turn. On each turn the player (the user) make a guess by entering a character from the keyboard. And on each turn we would like to check whether the user has made a guess or not. Therefore, on each iteration we define a special variable `guessed_any` to check if there was a guess. At the beginning of the turn there were no guesses, of course (because the turn has just started), therefore initially we set `guessed_any`  to False. Later, if the user has guessed a character on this turn we change the value `guessed_any` to True.

**Comment by bodrovis** [comment]
@ImprovementMajor 

`guessed_any = True`, line 41

This is a solution I came up with to check whether there was a guess or not (and this check is performed on each turn). So, how does it work? Using this code

```python
    for index, correct_character in enumerate(word):
        if correct_character == guess_character:
            guessed_any = True 
            guess_word[index] = guess_character
```

we are checking if the character entered by the user was found in the word (the answer to the question).

Next, we would like to display some output for the user saying whether a guess was found or not. We use this code:

```python
    if guessed_any:
        print("Please show us the letter ", guess_character)
    else:
        print("There is no " + guess_character + " in this word")
```

So, effectively the purpose of the `guessed_any` variable is to decide what string we have to display, nothing more. Can we get rid of this `guessed_any` variable? Of course! Let's print the text only if the user has made a guess:

```python
for index, correct_character in enumerate(word):
    if correct_character == guess_character:
        print("Please open character", guess_character)
        guess_word[index] = guess_character
```

Would that work? Surely it will. But there are two problems:

1. We do not output anything if the user's guess is wrong (the `word` does not contain the `guess_character` that the user has entered)
2. If the user has entered a character that is found multiple times in the word (for example, `a` is found 3 times in `banana`), it means that we are going to display the same message `Please open character` multiple times. That's, shall we say, is too much, IMHO.

Therefore, to overcome these 2 issues I'm proposing to create a special variable `guessed_any` which acts as a flag or a status saying if the guess was found on this turn. I'm not saying that's the only solution to this problem: perhaps, it's possible to think of something else. Usually, in programming there are multiple ways of solving the same task.

**Comment by bodrovis** [comment]
If the above does not help, I believe we need to draw a special trace table and discuss what happens on each iteration step by step. Please let me know, I can prepare the necessary materials

**Comment by ImprovementMajor** [comment]
@bodrovis Thank you very much, I got it. I'll just proceed with the homework, and will write to you if I get stuck.

**Comment by ImprovementMajor** [comment]
@bodrovis Hello Ilya! I have some difficulties with homework. I'm traveling again today and tomorrow. Will you be available on Tuesday between yours 16.00 - 21.00 pm? Wednesday works for me as well. Please let me know when it's convenient for you to arrange a skype call?
Thank you!

**Comment by bodrovis** [comment]
@ImprovementMajor Hello! Yes, Tuesday is fine. I'll be online starting from launch time then

**Comment by ImprovementMajor** [comment]
@bodrovis Thank you!

**Comment by ImprovementMajor** [comment]
@bodrovis Hello Ilya! Please let me know when I can call?

**Comment by bodrovis** [comment]
@ImprovementMajor Sorry, for some reason I must've missed a notification (I was overwhelmed by some issues on GH). I'm online atm and will also be available tomorrow (or, we can pick some other day)
