### ISSUE TITLE
CatProgram

### ISSUE THREAD

**Issue by ImprovementMajor** [ImprovementMajor/NewNew#7]
@bodrovis Hello Ilya! Can you please take a look at my questions? 
https://github.com/ImprovementMajor/NewNew/commit/e14bbbedb0fc7da80a0f923eb80e596d78276044

**Comment by bodrovis** [comment]
Hi, sure, I'll do it today!

**Comment by bodrovis** [comment]
@ImprovementMajor Would you please copy-paste the task from the course that you were trying to solve?

**Comment by bodrovis** [comment]
If you'd like, we can arrange a call today.

**Comment by ImprovementMajor** [comment]
@bodrovis Sorry, I've just seen your message. Here is the task
https://learn.moscoding.ru/courses/take/first/texts/12787447
Использование функций на практике
Теперь мы знаем как создавать функции. Давайте применим это знание и усовершенствуем программу, решающую задачу о кошке. Чтобы понять, какие функции нам потребуются, следует ответить на вопрос "Какие основные действия выполняет программа?". Таких действий два:

Расчёт радиуса.
Проверка, сумеет ли пройти кошка.
Начнём с расчёта радиуса:

def circle_radius(length):
    return length / (2 * 3.14)
В данном случае сначала вычисляется выражение length / (2 * 3.14), а затем возвращается полученный результат.

Функция для проверки пролезет ли кошка должна возвращать логическое значение. В этом случае функцию можно будет использовать в условных выражениях:

def cat_passes(height):
    return height >= 15
Теперь используем эти две функции:

space_for_cat = (circle_radius(1001) - circle_radius(1000)) * 100

print("Расстояние:", space_for_cat)

if cat_passes(space_for_cat):
    print("Кошка легко пролезет!")
else:
    print("Кошка не пройдёт!")
Программа разбита на логические блоки, а, кроме того, стала более удобочитаемой.

Теперь решим вопрос с "магическими" числами. Можно, конечно, написать комментарии, объяснив, что 3.14 - это число Пи, а 15 - средняя высота кошки. Однако по возможности я советовал бы писать самодокументирующийся код, то есть такой код, который понятен безо всяких комментариев. Это, конечно, не означает, что комментарии не нужны вовсе.

# Calculates radius of a circle based on a circle length
# Formula: length / (2 * Pi)
# @params length [Integer, Float]
# @return [Float]
def circle_radius(length):
    return length / (2 * 3.14)

# Checks if a cat fits the given heights
# @params height [Integer, Float]
# @return [Boolean]
def cat_passes(height):
    avg_cat_height = 15
    return height >= avg_cat_height
Для каждой функции мы добавляем комментарий с кратким описанием, списком аргументов и типом возвращаемого значения. "Магическое" число (высота кошки в холке) теперь хранится в переменной, по имени которой можно понять её назначение. Однако проблема в том, что avg_cat_height - это постоянное значение в программе, и оно не подразумевает изменения. Такое значение можно оформить в виде константы (то есть постоянного значения). Константы принято записывать заглавными буквами, обычно в начале программы:

AVG_CAT_HEIGHT = 15

# Checks if a cat fits the given heights
# @params height [Integer, Float]
# @return [Boolean]
def cat_passes(height):
    return height >= AVG_CAT_HEIGHT
Теперь мы более точно выразили свои намерения: AVG_CAT_HEIGHT - это постоянное значение, модифицировать которое не следует.

К сожалению, в Python нет простого способа запретить присваивать константе новые значения. По большому счёту, AVG_CAT_HEIGHT - это всё равно имя переменной, только записанное заглавными буквами. Однако большинство разработчиков поймёт, что вы подразумеваете именно создание константы.
А что мы будем делать с числом Пи? Тоже оформим как константу? Это возможное решение, но дело в том, что число Пи имеет гораздо больше, чем два знака после запятой. Тогда что нам делать? Указать столько знаков, сколько получится? Всё-таки не хотелось бы изобретать велосипед. К счастью, в Python есть модуль math, который умеет, в числе прочего, возвращать число Пи. Давайте используем его:

import math
AVG_CAT_HEIGHT = 15

# Calculates radius of a circle based on a circle length
# Formula: length / (2 * Pi)
# @params length [Integer, Float]
# @return [Float]
def circle_radius(length):
    return length / (2 * math.pi)

# остальной код
Теперь наша программа выглядит куда лучше. Мы избавились от дублирующегося кода, задокументировали функции, и разбили программу на логические блоки.

**Comment by ImprovementMajor** [comment]
@bodrovis I can do call tomorrow anytime starting 2pm your time. But you'll probably celebrate New Years evening starting that time, so we can talk on January 1st instead as well

**Comment by bodrovis** [comment]
@ImprovementMajor As a matter of fact, I'll be online
